---
title: "ADMH coding"
author: "Elena Iurlova"
date: "2024-10-12"
output: html_document
---

<style type="text/css">
body{
  font-family: Helvetica;
  font-size: 12pt;
}
/* Headers */
h1, h2{
  font-size: 16pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(openxlsx)
library (lubridate)
library (stringr)

# data format conversion
func <- function (x) { date =format(as.Date(x, 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y")
                      return (date)}

reform_date <- function (x) {
  function (x) { date =format(as.Date(x, 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y")
                      return (date)}
  
  y <- ifelse (str_detect (x, ".*[0-9].*"), func(x), "")
  return (y) }
```

Загрузка данных

```{r upload}
adsl_list <- read.xlsx("./ADaM-like/ADSL.xlsx")

mh_ds <- read.xlsx("./SDTM/MH_MEDICALHISTORY.xlsx")
```

Из домена ADSL возьмем переменные:

STUDYID
USUBJID
TRTP
TRTPN

```{r dm}
mh_subj <- 
  adsl_list %>% 
  select(STUDYID, SUBJID, USUBJID, TRTP, TRTPN) 
```

Согласно спецификации, извлечем из medical history (MH) :

MHSEQ 
MHCAT
MHTERM 
MHDECOD 
MHBODSYS
MHSTDTC
MHENDTC
AENDT
MHENRTPT

```{r}
mh_dt<- mh_ds %>% select (SUBJID, MHSEQ, MHCAT,MHTERM, MHDECOD, MHBODSYS, MHSTDTC, MHENDTC, MHENRTPT) %>%
          # Внесение пропущенныx значения в дату начала и конца исследования
                                 mutate (ASTDT = case_when (nchar(MHSTDTC) == 4 
                                                                 ~   paste0(MHSTDTC, "-01-01"),
                                                   nchar(MHSTDTC) == 7 
                                                                 ~ paste0(MHSTDTC, "-01"),
                                                   is.na (MHSTDTC) ~ '',
                                                   TRUE ~ as.character(MHSTDTC)),
                                
                                AENDT = case_when (MHENRTPT == 'ONGOING' ~ '',
                                                  nchar(MHENDTC) == 4 
                                                                 ~ paste0(MHENDTC, "-01-01"),
                                                   nchar(MHENDTC) == 7 
                                                                 ~ paste0(MHENDTC, "-01"),
                                                   is.na (MHENDTC) ~ ''))  %>%
          # Применение функции для форматирования даты, с сохранением пустых ячеек, где даты нет
                                mutate(ASTDT = ifelse (str_detect (ASTDT, ".*[0-9].*"), func(ASTDT), ""),
                                      AENDT = ifelse (str_detect (AENDT, ".*[0-9].*"), func(AENDT), "")) %>%
          # Создание флагов              
                                mutate (ASTDTF = case_when (is.na (MHSTDTC) |nchar(MHSTDTC) < 4  ~ "Y",
                                                    nchar(MHSTDTC) == 4 ~ "M",
                                                    nchar(MHSTDTC) == 7 ~ "D",
                                                   TRUE ~ ""),
                                
                                AENDTF = case_when (is.na (MHENDTC) |nchar(MHENDTC) < 4  ~ "Y",
                                                    nchar(MHENDTC) == 4 ~ "M",
                                                    nchar(MHENDTC) == 7 ~ "D",
                                                    TRUE ~ ""), 
        
                                MHENRF = ifelse (MHENRTPT == 'ONGOING', 'ONGOING', ""))
                                
```

```{r}
ADMH <- left_join(mh_dt, mh_subj) %>% select (STUDYID,
                                             USUBJID,
                                             TRTP,
                                             TRTPN,
                                             MHSEQ,
                                             MHCAT,
                                             MHTERM, 
                                             MHDECOD, 
                                             MHBODSYS,
                                             MHSTDTC,
                                             ASTDT,
                                             ASTDTF,
                                             MHENDTC,
                                             AENDT,
                                             AENDTF,
                                             MHENRTPT,
                                             MHENRF) %>% filter (!is.na (MHTERM))
ADMH
```

```{r}
write.xlsx(ADMH, "./ADaM-like/ADHM.xlsx")
```

